apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3rxi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-3rxi@sha256:97fc0e4a27a5f790c51d57cdfe3d6ff79a0ed94132d92c889e8aaf053d8306f4
        name: my-nodejs
        resources: {}
status: {}
